"""add |Source

Revision ID: 08b55b65003a
Revises: 54400183d3ef
Create Date: 2026-08-13 10:18:33.641787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b55b65003a'
down_revision: Union[str, Sequence[str], None] = '54400183d3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Jobs', 'source')
    # ### end Alembic commands ###
