"""add generate cv table, rework candidateprofile table

Revision ID: 090960a4bf8f
Revises: 68ddba0e0290
Create Date: 2026-10-03 11:39:57.082326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090960a4bf8f'
down_revision: Union[str, Sequence[str], None] = '68ddba0e0290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vac_cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vac_rew_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('education', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('frameworks', sa.String(), nullable=False),
    sa.Column('sqls', sa.String(), nullable=False),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('projects', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['Jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_answer.id'], ),
    sa.ForeignKeyConstraint(['vac_rew_id'], ['job_ai_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_answer', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('location', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('user_answer', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('user_answer', sa.Column('expirience', sa.Text(), nullable=False))
    op.add_column('user_answer', sa.Column('education', sa.Text(), nullable=False))
    op.add_column('user_answer', sa.Column('langs', sa.Text(), nullable=False))
    op.add_column('user_answer', sa.Column('projects', sa.Text(), nullable=False))
    op.add_column('user_answer', sa.Column('github', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('ln', sa.String(), nullable=False))
    op.add_column('user_answer', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('user_answer', sa.Column('upd_at', sa.Date(), nullable=True))
    op.alter_column('user_answer', 'skills',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_answer_telegram_id'), 'user_answer', ['telegram_id'], unique=False)
    op.drop_column('user_answer', 'remote')
    op.drop_column('user_answer', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_answer', sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_answer_telegram_id'), table_name='user_answer')
    op.alter_column('user_answer', 'skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_answer', 'upd_at')
    op.drop_column('user_answer', 'created_at')
    op.drop_column('user_answer', 'ln')
    op.drop_column('user_answer', 'github')
    op.drop_column('user_answer', 'projects')
    op.drop_column('user_answer', 'langs')
    op.drop_column('user_answer', 'education')
    op.drop_column('user_answer', 'expirience')
    op.drop_column('user_answer', 'summary')
    op.drop_column('user_answer', 'telegram_id')
    op.drop_column('user_answer', 'location')
    op.drop_column('user_answer', 'email')
    op.drop_column('user_answer', 'phone')
    op.drop_column('user_answer', 'name')
    op.drop_table('vac_cv')
    # ### end Alembic commands ###
