"""make ai review fields nullable1

Revision ID: 0bfb58a201c7
Revises: b09d35d5fdd6
Create Date: 2026-09-21 14:02:00.869240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfb58a201c7'
down_revision: Union[str, Sequence[str], None] = 'b09d35d5fdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_ai_reviews', 'match_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_ai_reviews', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_ai_reviews', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_ai_reviews', 'match_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
