"""added f_seen&l_seen

Revision ID: 136784d5d2cf
Revises: 90ebefeed4bb
Create Date: 2026-08-14 19:34:39.688433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136784d5d2cf'
down_revision: Union[str, Sequence[str], None] = '90ebefeed4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('first_seen', sa.String(), nullable=True))
    op.add_column('Jobs', sa.Column('last_seen', sa.String(), nullable=True))
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_answer', 'main_prof',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_answer', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_answer', 'frameworks',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_answer', 'sqls',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_answer', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_answer', 'remote',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answer', 'remote',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_answer', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_answer', 'sqls',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_answer', 'frameworks',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_answer', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_answer', 'main_prof',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Jobs', 'last_seen')
    op.drop_column('Jobs', 'first_seen')
    # ### end Alembic commands ###
