"""addon snippet&updated

Revision ID: 54400183d3ef
Revises: 35edb6895d6b
Create Date: 2026-08-12 17:43:40.543522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54400183d3ef'
down_revision: Union[str, Sequence[str], None] = '35edb6895d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Jobs', sa.Column('snippet', sa.String(), nullable=True))
    op.add_column('Jobs', sa.Column('updated', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Jobs', 'updated')
    op.drop_column('Jobs', 'snippet')
    # ### end Alembic commands ###
