"""added f_seen&l_seen rework 

Revision ID: 7f1289a91f5e
Revises: 136784d5d2cf
Create Date: 2026-08-14 20:43:04.624463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1289a91f5e'
down_revision: Union[str, Sequence[str], None] = '136784d5d2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'first_seen',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='first_seen::date')
    op.alter_column('Jobs', 'last_seen',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='last_seen::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'last_seen',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Jobs', 'first_seen',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
