"""added candidate profile

Revision ID: 90ebefeed4bb
Revises: 08b55b65003a
Create Date: 2026-08-13 15:27:56.466597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ebefeed4bb'
down_revision: Union[str, Sequence[str], None] = '08b55b65003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('main_prof', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('frameworks', sa.String(), nullable=True),
    sa.Column('sqls', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('user_answer')
    # ### end Alembic commands ###
