"""added f_seen&l_seen rework 2 

Revision ID: 95eb1c323c07
Revises: 7f1289a91f5e
Create Date: 2026-08-14 21:00:51.679513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eb1c323c07'
down_revision: Union[str, Sequence[str], None] = '7f1289a91f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='updated::date')
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'updated',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
