"""add job ai reviews

Revision ID: c85fded943b8
Revises: 95eb1c323c07
Create Date: 2026-09-21 13:35:12.918089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85fded943b8'
down_revision: Union[str, Sequence[str], None] = '95eb1c323c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_ai_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('missingskills', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('ai_checked_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['Jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Jobs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Jobs', 'snippet',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('job_ai_reviews')
    # ### end Alembic commands ###
